name: bk-test
channels:
  - conda-forge
dependencies:
  - python=3.7
  - boto
  - colorama
  - conda-build=3.18.10
  - conda-verify=3.4.2
  - nodejs>=10.13
  - packaging
  - ripgrep=0.10.0
  - setuptools
  - yaml
