name: Bokeh Release

on:
  repository_dispatch:
    types: [build]

env:
  CONDA_BASE_REQS: "conda=4.8.1 conda-build=3.18.10 conda-verify=3.4.2 ripgrep=0.10.0 jinja2"
  CONDA_ENV_REQS: "python=3.8 jinja2 yaml pyyaml"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Maintainer Authorization
        env:
          RELEASE_PASSWORD: ${{ secrets.RELEASE_PASSWORD }}
          REQUEST_PASSWORD: ${{ github.event.client_payload.release_password }}
        run:
          if [ $REQUEST_PASSWORD == $RELEASE_PASSWORD ]; then
            echo "Maintainer release password confirmed, proceeding with release"
          else
            echo "Maintainer release password incorrect, aborting release"
            exit 1
          fi

      - uses: actions/checkout@v2-beta
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: bk-test
          environment-file: ci/environment-build.yml

      - name: Build Assets
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          BOKEH_VERSION: ${{ github.event.client_payload.version }}
          SLACK_TOKEN: ${{ secrets.SLACK_BUILD_RELEASE_TOKEN }}
        run: |
          python -m release build --notify-slack ${BOKEH_VERSION}
