name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build a release for"
        required: true

env:
  CONDA_BASE_REQS: "conda=4.8.1 conda-build=3.18.10 conda-verify=3.4.2 ripgrep=0.10.0 jinja2"
  CONDA_ENV_REQS: "python=3.8 jinja2 yaml pyyaml"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Maintainer Authorization
        run: |
          echo ${{github.actor}}
          exit 1

      - uses: actions/checkout@v2-beta
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: bk-test
          environment-file: ci/environment-build.yml

      - name: Build Assets
        env:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          BOKEH_VERSION: ${{ github.event.client_payload.version }}
          SLACK_TOKEN: ${{ secrets.SLACK_BUILD_RELEASE_TOKEN }}
        run: |
          echo "build build"
